// This file is automatically generated

#pragma warning disable CS8618
#pragma warning disable CS0219

using HogWarpSdk;
using HogWarpSdk.Game;
using HogWarpSdk.Systems;
using HogWarpSdk.Internal;

namespace HogWarp.Replicated
{
    [Replicated(Class = "/PiNotifications/Actors/BP_PI_Notifications.BP_PI_Notifications", Hash = 4907751509687132419)]
    public partial class BpPiNotifications : Actor
    {
        [ClientRpc(Function = "TriggerNotification", Hash = 16932435715196875644)]
        public void TriggerNotification(Player player, int iconIdx, string title, string message, float duration)
        {
            ushort length = 0;
            var data = IBuffer.Create();
            try
            {
                data.WriteInt32(iconIdx);
                data.WriteString(title);
                data.WriteString(message);
                data.WriteFloat(duration);

                IRpc.Get().Call(player.InternalPlayer, Id, 4907751509687132419, 16932435715196875644, data);
            }
            finally
            {
                IBuffer.Release(data);
            }
        }
    }
}
