// This file is automatically generated

#pragma warning disable CS8618
#pragma warning disable CS0219

using HogWarpSdk;
using HogWarpSdk.Game;
using HogWarpSdk.Systems;
using HogWarpSdk.Internal;

namespace HogWarp.Replicated
{
    [Replicated(Class = "/Notifications/Actors/BpNotification.BpNotification", Hash = 13084089758305893838)]
    public partial class BpNotification : Actor
    {
        [ClientRpc(Function = "TriggerNotification", Hash = 16932435715196875644)]
        public void TriggerNotification(Player player, string title, string message, float duration)
        {
            ushort length = 0;
            var data = IBuffer.Create();
            try
            {
                data.WriteString(title);
                data.WriteString(message);
                data.WriteFloat(duration);
                
                IRpc.Get().Call(player.InternalPlayer, Id, 13084089758305893838, 16932435715196875644, data);
            }
            finally
            {
                IBuffer.Release(data);
            }
        }
    }
}
