// This file is automatically generated

#pragma warning disable CS8618
#pragma warning disable CS0219

using HogWarpSdk;
using HogWarpSdk.Game;
using HogWarpSdk.Systems;
using HogWarpSdk.Internal;

namespace HogWarp.Replicated
{
    [Replicated(Class = "/HogWarpChat/Actors/BpHogWarpChat.BpHogWarpChat", Hash = 15037094559503762690)]
    public partial class BpHogWarpChat : Actor
    {
        public partial void SendMsg(Player player, string message);

        [ServerRpc(Function = "SendMsg", Hash = 3936215300427668376)]
        public void SendMsg_Impl(Player player, IBuffer data)
        {
            ushort length = 0;
            var message = data.ReadString();
            
            SendMsg(player, message);
        }
        
        [ClientRpc(Function = "RecieveMsg", Hash = 12684788271436983199)]
        public void RecieveMsg(Player player, string message)
        {
            ushort length = 0;
            var data = IBuffer.Create();
            try
            {
                data.WriteString(message);
                
                IRpc.Get().Call(player.InternalPlayer, Id, 15037094559503762690, 12684788271436983199, data);
            }
            finally
            {
                IBuffer.Release(data);
            }
        }
    }
}
