// This file is automatically generated

#pragma warning disable CS8618
#pragma warning disable CS0219

using HogWarpSdk;
using HogWarpSdk.Game;
using HogWarpSdk.Systems;
using HogWarpSdk.Internal;

namespace HogWarp.Replicated
{
	[Replicated(Class = "/PiChat/Actors/BP_PI_Chat.BP_PI_Chat", Hash = 8123988857662102289)]
	public partial class BpPiChat : Actor
	{
		[ClientRpc(Function = "Initialize", Hash = 14179742977543924331)]
		public void Initialize(Player player, float height, float width, float textScale)
		{
			ushort length = 0;
			var data = IBuffer.Create();
			try
			{
				data.WriteFloat(height);
				data.WriteFloat(width);
				data.WriteFloat(textScale);

				IRpc.Get().Call(player.InternalPlayer, Id, 8123988857662102289, 14179742977543924331,
					data);
			}
			finally
			{
				IBuffer.Release(data);
			}
		}

		public partial void SaveSettings(Player player, float height, float width, float textScale);

		[ServerRpc(Function = "SaveSettings", Hash = 14966178339566806261)]
		public void SaveSettings_Impl(Player player, IBuffer data)
		{
			ushort length = 0;
			var height = data.ReadFloat();
			var width = data.ReadFloat();
			var textScale = data.ReadFloat();

			SaveSettings(player, height, width, textScale);
		}

		[ClientRpc(Function = "FromServer", Hash = 1267410493214679138)]
		public void FromServer(Player player, string message)
		{
			ushort length = 0;
			var data = IBuffer.Create();
			try
			{
				data.WriteString(message);

				IRpc.Get().Call(player.InternalPlayer, Id, 8123988857662102289, 1267410493214679138,
					data);
			}
			finally
			{
				IBuffer.Release(data);
			}
		}

		public partial void FromClient(Player player, string message);

		[ServerRpc(Function = "FromClient", Hash = 7083850986714470862)]
		public void FromClient_Impl(Player player, IBuffer data)
		{
			ushort length = 0;
			var message = data.ReadString();

			FromClient(player, message);
		}
	}
}
