// This file is automatically generated

#pragma warning disable CS8618
#pragma warning disable CS0219

using HogWarpSdk;
using HogWarpSdk.Game;
using HogWarpSdk.Systems;
using HogWarpSdk.Internal;

namespace HogWarp.Replicated
{
    [Replicated(Class = "/PillarsDialog/BpPillarsDialog.BpPillarsDialog", Hash = 11192085175838289190)]
    public partial class BpPillarsDialog : Actor
    {
        public partial void DialogResult(NativePlayer player, string dialogId, int result);

        [ServerRpc(Function = "DialogResult", Hash = 7791736367508744088)]
        public void DialogResult_Impl(Player player, IBuffer data)
        {
            ushort length = 0;
            var dialogId = data.ReadString();
            var result = data.ReadInt32();

            DialogResult(player, dialogId, result);
        }

        [ClientRpc(Function = "ShowDialog", Hash = 11389743689032709116)]
        public void ShowDialog(Player player, string dialogId, string title, string message)
        {
            ushort length = 0;
            var data = IBuffer.Create();
            try
            {
                data.WriteString(dialogId);
                data.WriteString(title);
                data.WriteString(message);

                IRpc.Get().Call(player.InternalPlayer, Id, 11192085175838289190, 11389743689032709116, data);
            }
            finally
            {
                IBuffer.Release(data);
            }
        }
    }
}
