// This file is automatically generated

#pragma warning disable CS8618
#pragma warning disable CS0219

using HogWarpSdk;
using HogWarpSdk.Game;
using HogWarpSdk.Systems;
using HogWarpSdk.Internal;

namespace HogWarp.Replicated
{
    [Replicated(Class = "/PiDialog/Actors/BpPiDialog.BpPiDialog", Hash = 10521616378621317223)]
    public partial class BpPiDialog : Actor
    {
        public partial void DialogResponse(Player player, string guid, int buttonType);

        [ServerRpc(Function = "DialogResponse", Hash = 11061340994812190018)]
        public void DialogResponse_Impl(Player player, IBuffer data)
        {
            ushort length = 0;
            var guid = data.ReadString();
            var buttonType = data.ReadInt32();
            
            DialogResponse(player, guid, buttonType);
        }
        
        [ClientRpc(Function = "ShowDialog", Hash = 11389743689032709116)]
        public void ShowDialog(Player player, string guid, int dialogType, string title, string message, string yesText, string noText, string cancelText)
        {
            ushort length = 0;
            var data = IBuffer.Create();
            try
            {
                data.WriteString(guid);
                data.WriteInt32(dialogType);
                data.WriteString(title);
                data.WriteString(message);
                data.WriteString(yesText);
                data.WriteString(noText);
                data.WriteString(cancelText);
                
                IRpc.Get().Call(player.InternalPlayer, Id, 10521616378621317223, 11389743689032709116, data);
            }
            finally
            {
                IBuffer.Release(data);
            }
        }
    }
}
